In [12]:
pip install pandas

Requirement already satisfied: pandas in c:\users\asmit\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asmit\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asmit\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asmit\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asmit\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asmit\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [3]:
data=[10,20,30]
s=pd.Series(data)
print(s)

0    10
1    20
2    30
dtype: int64

In [6]:
data={
    "Name":["A","B","C","D","E","F","G","H","I","J"],
    "Age":[20,30,34,35,36,37,38,39,40,50]
}
df=pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   30
2    C   34
3    D   35
4    E   36
5    F   37
6    G   38
7    H   39
8    I   40
9    J   50

In [7]:
df.head()

  Name  Age
0    A   20
1    B   30
2    C   34
3    D   35
4    E   36

In [8]:
df.tail()

  Name  Age
5    F   37
6    G   38
7    H   39
8    I   40
9    J   50

In [10]:
df.shape

(10, 2)

In [11]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

In [13]:
df=pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [14]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [15]:
df.shape

(8807, 12)

In [16]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [18]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [19]:
df['title']

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: object

In [22]:
df[['title','type','country']]

                      title     type        country
0      Dick Johnson Is Dead    Movie  United States
1             Blood & Water  TV Show   South Africa
2                 Ganglands  TV Show            NaN
3     Jailbirds New Orleans  TV Show            NaN
4              Kota Factory  TV Show          India
...                     ...      ...            ...
8802                 Zodiac    Movie  United States
8803            Zombie Dumb  TV Show            NaN
8804             Zombieland    Movie  United States
8805                   Zoom    Movie  United States
8806                 Zubaan    Movie          India

[8807 rows x 3 columns]

In [23]:
df.iloc[0]

show_id                                                        s1
type                                                        Movie
title                                        Dick Johnson Is Dead
director                                          Kirsten Johnson
cast                                                          NaN
country                                             United States
date_added                                     September 25, 2021
release_year                                                 2020
rating                                                      PG-13
duration                                                   90 min
listed_in                                           Documentaries
description     As her father nears the end of his life, filmm...
Name: 0, dtype: object

In [24]:
df.iloc[200]

show_id                                                      s201
type                                                        Movie
title                                             Krishna Cottage
director                                            Santram Varma
cast            Sohail Khan, Isha Koppikar, Natassha, Rati Agn...
country                                                     India
date_added                                        August 27, 2021
release_year                                                 2004
rating                                                      TV-14
duration                                                  124 min
listed_in       Action & Adventure, Horror Movies, Internation...
description     True love is put to the test when another woma...
Name: 200, dtype: object

In [25]:
df.loc[0,'title']

'Dick Johnson Is Dead'

In [26]:
df.loc[200,'title']

'Krishna Cottage'

In [27]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [30]:
df['director']=df['director'].fillna('Unknown')

In [31]:
df.isnull().sum()

show_id           0
type              0
title             0
director          0
cast            825
country         831
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
dtype: int64

In [33]:
df['cast']=df['cast'].fillna('Unknown')

In [34]:
df['country']=df['country'].fillna('Unknown')

In [36]:
df['date_added']=df['date_added'].fillna('Unknown')

In [38]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          4
duration        3
listed_in       0
description     0
dtype: int64

In [39]:
df['rating']=df['rating'].fillna('Unknown')

In [40]:
df['duration']=df['duration'].fillna('Unknown')

In [41]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [42]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [44]:
df['title'].value_counts()

title
Dick Johnson Is Dead                     1
Ip Man 2                                 1
Hannibal Buress: Comedy Camisado         1
Turbo FAST                               1
Masha's Tales                            1
                                        ..
Love for Sale 2                          1
ROAD TO ROMA                             1
Good Time                                1
Captain Underpants Epic Choice-o-Rama    1
Zubaan                                   1
Name: count, Length: 8807, dtype: int64

In [47]:
df['country'].value_counts().head(10)

country
United States     2818
India              972
Unknown            831
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Name: count, dtype: int64

In [50]:
df['date_added'].value_counts().sort_index().head(10)

date_added
April 15, 2018      1
April 16, 2019      1
April 17, 2016      1
April 20, 2017      1
April 4, 2017       1
August 1, 2017      1
August 13, 2018     1
August 21, 2017     1
August 4, 2017      3
December 1, 2018    1
Name: count, dtype: int64

In [49]:
df['rating'].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
Unknown        4
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [51]:
movies=df[df['type']=='Movie']

In [52]:
print(movies)

     show_id   type                             title  \
0         s1  Movie              Dick Johnson Is Dead
6         s7  Movie  My Little Pony: A New Generation
7         s8  Movie                           Sankofa
9        s10  Movie                      The Starling
12       s13  Movie                      Je Suis Karl
...      ...    ...                               ...
8801   s8802  Movie                           Zinzana
8802   s8803  Movie                            Zodiac
8804   s8805  Movie                        Zombieland
8805   s8806  Movie                              Zoom
8806   s8807  Movie                            Zubaan

                           director  \
0                   Kirsten Johnson
6     Robert Cullen, José Luis Ucha
7                      Haile Gerima
9                    Theodore Melfi
12              Christian Schwochow
...                             ...
8801                Majid Al Ansari
8802                  David Fincher
8804                Ruben Fleischer
8805                   Peter Hewitt
8806                    Mozez Singh

                                                   cast  \
0                                               Unknown
6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
9     Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
12    Luna Wedler, Jannis Niewöhner, Milan Peschel, ...
...                                                 ...
8801  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

                                                country          date_added  \
0                                         United States  September 25, 2021
6                                               Unknown  September 24, 2021
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
9                                         United States  September 24, 2021
12                              Germany, Czech Republic  September 23, 2021
...                                                 ...                 ...
8801                       United Arab Emirates, Jordan       March 9, 2016
8802                                      United States   November 20, 2019
8804                                      United States    November 1, 2019
8805                                      United States    January 11, 2020
8806                                              India       March 2, 2019

      release_year rating duration  \
0             2020  PG-13   90 min
6             2021     PG   91 min
7             1993  TV-MA  125 min
9             2021  PG-13  104 min
12            2021  TV-MA  127 min
...            ...    ...      ...
8801          2015  TV-MA   96 min
8802          2007      R  158 min
8804          2009      R   88 min
8805          2006     PG   88 min
8806          2015  TV-14  111 min

                                             listed_in  \
0                                        Documentaries
6                             Children & Family Movies
7     Dramas, Independent Movies, International Movies
9                                     Comedies, Dramas
12                        Dramas, International Movies
...                                                ...
8801           Dramas, International Movies, Thrillers
8802                    Cult Movies, Dramas, Thrillers
8804                           Comedies, Horror Movies
8805                Children & Family Movies, Comedies
8806    Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
6     Equestria's divided. But a bright-eyed hero be...
7     On a photo shoot in Ghana, an American model s...
9     A woman adjusting to life after a loss contend...
12    After most of her family is murdered in a terr...
...                                                 ...
8801  Recovering alcoholic Talal wakes up inside a s...
8802  A political cartoonist, a crime reporter and a...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[6131 rows x 12 columns]

In [57]:
recent=df[df['release_year']>2020]

In [59]:
print(recent)

     show_id     type                      title         director  \
1         s2  TV Show              Blood & Water          Unknown
2         s3  TV Show                  Ganglands  Julien Leclercq
3         s4  TV Show      Jailbirds New Orleans          Unknown
4         s5  TV Show               Kota Factory          Unknown
5         s6  TV Show              Midnight Mass    Mike Flanagan
...      ...      ...                        ...              ...
1468   s1469    Movie  What Happened to Mr. Cha?     Kim Dong-kyu
1551   s1552  TV Show                      Hilda          Unknown
1696   s1697  TV Show               Polly Pocket          Unknown
2920   s2921  TV Show              Love Is Blind          Unknown
8437   s8438  TV Show     The Netflix Afterparty          Unknown

                                                   cast  \
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                               Unknown
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
5     Kate Siegel, Zach Gilford, Hamish Linklater, H...
...                                                 ...
1468           Cha In-pyo, Cho Dal-hwan, Song Jae-ryong
1551  Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...
1696  Emily Tennant, Shannon Chan-Kent, Kazumi Evans...
2920                        Nick Lachey, Vanessa Lachey
8437       David Spade, London Hughes, Fortune Feimster

                                    country          date_added  release_year  \
1                              South Africa  September 24, 2021          2021
2                                   Unknown  September 24, 2021          2021
3                                   Unknown  September 24, 2021          2021
4                                     India  September 24, 2021          2021
5                                   Unknown  September 24, 2021          2021
...                                     ...                 ...           ...
1468                            South Korea     January 1, 2021          2021
1551  United Kingdom, Canada, United States   December 14, 2020          2021
1696         Canada, United States, Ireland   November 15, 2020          2021
2920                          United States   February 13, 2020          2021
8437                          United States     January 2, 2021          2021

     rating   duration                                          listed_in  \
1     TV-MA  2 Seasons    International TV Shows, TV Dramas, TV Mysteries
2     TV-MA   1 Season  Crime TV Shows, International TV Shows, TV Act...
3     TV-MA   1 Season                             Docuseries, Reality TV
4     TV-MA  2 Seasons  International TV Shows, Romantic TV Shows, TV ...
5     TV-MA   1 Season                 TV Dramas, TV Horror, TV Mysteries
...     ...        ...                                                ...
1468  TV-MA    102 min                     Comedies, International Movies
1551  TV-Y7  2 Seasons                                           Kids' TV
1696   TV-Y  2 Seasons                                           Kids' TV
2920  TV-MA   1 Season                      Reality TV, Romantic TV Shows
8437  TV-MA   1 Season          Stand-Up Comedy & Talk Shows, TV Comedies

                                            description
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
5     The arrival of a charismatic young priest brin...
...                                                 ...
1468  With the peak of his career long behind him, a...
1551  Fearless, free-spirited Hilda finds new friend...
1696  After uncovering a magical locket that allows ...
2920  Nick and Vanessa Lachey host this social exper...
8437  Hosts David Spade, Fortune Feimster and London...

[592 rows x 12 columns]

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("netflix_titles.csv")

In [3]:
df.groupby('type').size()

type
Movie      6131
TV Show    2676
dtype: int64

In [4]:
df.groupby(['release_year','type']).size()

release_year  type
1925          TV Show      1
1942          Movie        2
1943          Movie        3
1944          Movie        3
1945          Movie        3
                        ...
2019          TV Show    397
2020          Movie      517
              TV Show    436
2021          Movie      277
              TV Show    315
Length: 119, dtype: int64

In [6]:
df.sort_values(by='release_year',ascending=True)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
...,...,...,...,...,...,...,...,...,...,...,...,...
862,s863,TV Show,Special,NaN,"Ryan O'Connell, Jessica Hecht, Punam Patel, Ma...",United States,"May 20, 2021",2021,TV-MA,2 Seasons,TV Comedies,A young gay man with cerebral palsy branches o...
861,s862,Movie,Little Singham Future mein Satakli,Prakash Satam,"Anamaya Verma, Ganesh Divekar, Jigna Bharadhwa...",NaN,"May 20, 2021",2021,TV-Y7,47 min,"Children & Family Movies, Comedies",Little Singham and his crew travel to the year...
857,s858,TV Show,The Neighbor,NaN,"Quim Gutiérrez, Clara Lago, Adrián Pino, Catel...",Spain,"May 21, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",Self-centered Javier's life gets a bit messy w...
876,s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...
965,s966,TV Show,Yasuke,NaN,"LaKeith Stanfield, Takehiro Hira, Maya Tanida,...",NaN,"April 29, 2021",2021,TV-MA,1 Season,"Anime Series, International TV Shows",A peaceful boatman once known as the Black Sam...

In [8]:
df.sort_values(by='duration',ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1329,s1330,Movie,The Misadventures of Hedi and Cokeman,Julien Royal,"Hedi Bouchenafa, Nassim Lyes, Fred Testot, Jul...",France,"February 10, 2021",2021,TV-MA,99 min,"Comedies, International Movies","In Paris, two dysfunctional dealers use family..."
6278,s6279,Movie,Being AP,Anthony Wonke,Tony McCoy,United Kingdom,"August 15, 2016",2015,TV-14,99 min,"Documentaries, International Movies, Sports Mo...","With retirement staring him in the face, an al..."
952,s953,Movie,The Whole Nine Yards,Jonathan Lynn,"Bruce Willis, Matthew Perry, Rosanna Arquette,...",United States,"May 1, 2021",2000,R,99 min,"Action & Adventure, Comedies",An unhappily married dentist becomes mixed up ...
6141,s6142,Movie,American Hangman,Wilson Coneybeare,"Donald Sutherland, Vincent Kartheiser, Oliver ...",Canada,"July 30, 2019",2019,TV-MA,99 min,Thrillers,A judge’s kidnapping is streamed live on socia...
929,s930,Movie,Dead Again in Tombstone,Roel Reiné,"Danny Trejo, Jake Busey, Elysia Rotaru, Dean M...",NaN,"May 1, 2021",2017,R,99 min,"Action & Adventure, Horror Movies","At the devil's bidding, a deceased outlaw retu..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6556,s6557,TV Show,Dance Academy,NaN,"Xenia Goodwin, Alicia Banit, Dena Kaplan, Isab...",Australia,"December 20, 2017",2013,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Fifteen-year-old Tara Webster's dream of danci...
2945,s2946,TV Show,Cagaster of an Insect Cage,NaN,"Yoshimasa Hosoya, Kana Hanazawa, Natsuki Hanae...",Japan,"February 6, 2020",2020,TV-MA,1 Season,"Anime Series, International TV Shows",Thirty years after a disease that turns the in...
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [24]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")


#clean date added column #strip is use to remove spaces from both left and right side
df['date_added'] = df['date_added'].str.strip()


#convert to date format
#september 9 2021 convert to 2021-09-09
df['date_added'] = pd.to_datetime(df['date_added'],errors='coerce')

#Extract year
df['year_added'] = df['date_added'].dt.year

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
 12  year_added    8797 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(10)
memory usage: 894.6+ KB

In [27]:
df['title'].str.upper()

0        DICK JOHNSON IS DEAD
1               BLOOD & WATER
2                   GANGLANDS
3       JAILBIRDS NEW ORLEANS
4                KOTA FACTORY
                ...
8802                   ZODIAC
8803              ZOMBIE DUMB
8804               ZOMBIELAND
8805                     ZOOM
8806                   ZUBAAN
Name: title, Length: 8807, dtype: object

In [28]:
df[df['title'].str.contains('Love',na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
25,s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell,Australia,2021-09-21,2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...,2021.0
158,s159,Movie,Love Don't Cost a Thing,Troy Byer,"Nick Cannon, Christina Milian, Kenan Thompson,...",United States,2021-09-01,2003,PG-13,101 min,"Comedies, Romantic Movies",A nerdy teen tries to make himself cool by ass...,2021.0
159,s160,Movie,Love in a Puff,Pang Ho-cheung,"Miriam Chin Wah Yeung, Shawn Yue, Singh Hartih...",Hong Kong,2021-09-01,2010,TV-MA,103 min,"Comedies, Dramas, International Movies",When the Hong Kong government enacts a ban on ...,2021.0
206,s207,Movie,"LSD: Love, Sex Aur Dhokha",Dibakar Banerjee,"Nushrat Bharucha, Anshuman Jha, Neha Chauhan, ...",India,2021-08-27,2010,TV-MA,112 min,"Dramas, Independent Movies, International Movies",This provocative drama examines how the voyeur...,2021.0
227,s228,Movie,Really Love,Angel Kristi Williams,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,2021-08-25,2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8567,s8568,TV Show,The Year of Happiness and Love,NaN,"Amber Kuo, James Wen, Weber Yang, Sonia Sui, N...",Taiwan,2016-09-01,2009,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Jiang Chen-bo is a loser without prospects for...,2016.0
8575,s8576,TV Show,This Is My Love,NaN,"Jin-mo Joo, Sa-rang Kim, Junior, Ja-in Lee, Su...",South Korea,2017-05-22,2015,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",A renowned actor who is still pining over the ...,2017.0
8649,s8650,Movie,Two Lovers and a Bear,Kim Nguyen,"Dane DeHaan, Tatiana Maslany, Gordon Pinsent, ...",Canada,2017-05-02,2016,R,95 min,"Dramas, Independent Movies, Romantic Movies",A troubled couple living near the North Pole b...,2017.0
8721,s8722,TV Show,What Is Love?,NaN,"Chris Wu, Jade Chou, Duncan Lai, King Chin, Ki...",Taiwan,2017-01-01,2012,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A 32-year-old romantic looking for a long-term...,2017.0
8725,s8726,Movie,What's Up With Love?,"Rudy Soedjarwo, Riri Riza","Dian Sastrowardoyo, Nicholas Saputra, Ladya Ch...",Indonesia,2018-12-08,2002,R,110 min,"Dramas, International Movies, Romantic Movies",A popular high school girl strains her relatio...,2018.0

In [31]:
df['year_added']=df['year_added'].astype('Int64')

In [38]:
print(df['year_added'])

0       2021
1       2021
2       2021
3       2021
4       2021
        ...
8802    2019
8803    2019
8804    2019
8805    2020
8806    2019
Name: year_added, Length: 8807, dtype: Int64

In [39]:
df['is_recent'] = df['release_year'].apply(lambda x:"Yes" if x > 2018 else "No")

In [41]:
print(df['is_recent'])

0       Yes
1       Yes
2       Yes
3       Yes
4       Yes
       ...
8802     No
8803     No
8804     No
8805     No
8806     No
Name: is_recent, Length: 8807, dtype: object